#!/bin/bash

MODE="$1"
LOGINHOSTUSER="$2"
set -e

SCRIPTDIR=$(cd -P $(dirname "$0"); pwd -P)

LINUXVER="3.9.y"
SOURCEDIR="$SCRIPTDIR/rpi-linux"
TOOLSDIR="$SCRIPTDIR/rpi-tools"
DISTDIR="$SCRIPTDIR/dist"
PKGFILE="$SCRIPTDIR/rpi-kernel.tar.gz"

BUILD_PROCESSORS="4"

XCOMPILE="${TOOLSDIR}/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/bin/arm-bcm2708hardfp-linux-gnueabi-"
ARCHTECTURE="arm"

chkcmd() { which $@ >/dev/null 2>&1; }
die() { echo $@ 1>&2; exit 1; }

distclean() {
    for d in "$SOURCEDIR" "$TOOLSDIR" "$DISTDIR" "$PKGFILE"; do
        [ -e "$d" ] && rm -rf "$d"
    done
}

dl_extract_rpi_linux() {
    curl -L -o - https://api.github.com/repos/raspberrypi/linux/tarball/rpi-${LINUXVER} | tar xzf -
    mv raspberrypi-linux-* ${SOURCEDIR}
}

dl_extract_rpi_tools() {
    curl -L -o -  https://api.github.com/repos/raspberrypi/tools/tarball/master | tar xzf -
    mv raspberrypi-tools-* ${TOOLSDIR}
}

make_rpi_linux() {
    (
        cd "$SOURCEDIR"
        make -j${BUILD_PROCESSORS} CROSS_COMPILE="${XCOMPILE}" ARCH="${ARCHTECTURE}" $@
    )
}

mkdistpackage() {
    local FAKEROOT=$(which fakeroot)
    make_rpi_linux INSTALL_MOD_PATH="$DISTDIR" modules_install
    [ ! -d "$DISTDIR/boot" ] && mkdir "$DISTDIR/boot"
    cp "$SOURCEDIR/arch/arm/boot/zImage" "$DISTDIR/boot/kernel.img"
    ${FAKEROOT} tar cf - -C "$DISTDIR" boot lib | gzip -9 > "$PKGFILE"
}

action() {
    case "$1" in
        all_dl_extract)
            dl_extract_rpi_linux
            dl_extract_rpi_tools
            ;;
        getconfig)
            [ -z "$LOGINHOSTUSER" ] && exit 1
            scp ${LOGINHOSTUSER}:/proc/config.gz ${SCRIPTDIR}
            ;;
        configure)
            if [ -e "$SCRIPTDIR/config.gz" ]; then
                gunzip -c "$SCRIPTDIR/config.gz" > "$SOURCEDIR/.config"
                mv "$SCRIPTDIR/config.gz" "$SCRIPTDIR/config.gz.applyed"
            fi
            make_rpi_linux menuconfig
            ;;
        build)  
            make_rpi_linux
            make_rpi_linux modules
            ;;
        mkdistpackage)
            mkdistpackage
            ;;
        distclean)
            distclean
            ;;
        *)
            echo "MODE is not specified."
            ;;
    esac
}


if [ "$MODE" = "all" ]; then
    action all_dl_extract
    action configure
    action build
    action mkdistpackage
else
    action $MODE
fi

